name: Push Source Files to Applanga
on:
  push:
    branches:
      - main
    paths:
      - package.json
  workflow_dispatch:
    inputs:
      push_targets:
        type: boolean
        description: Push translation files. If set translation files will be pushed instead of source files
        default: false
        required: false
      branch_id:
        description: Branch ID
        required: false
        type: string
jobs:
  push-sources-for-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Mobile App ID from Access Token
        id: extract-app-id
        run: 'echo "MOBILE_APP_ID=$(echo "${{ secrets.APPLANGA_ACCESS_TOKEN }}" | cut -d''!'' -f1)" >> $GITHUB_OUTPUT'
      - name: Notify workflow started
        run: |-
          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-start?app=${{ steps.extract-app-id.outputs.MOBILE_APP_ID }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
            -d '{
             "branchId": "${{ github.event.inputs.branch_id }}",
            "workflowType": "push"
            }' || echo "Failed to notify workflow start, continuing anyway"
      - uses: actions/checkout@v3
        with:
          path: checkout
      - uses: applanga/setup-applanga-cli@v1.0.3
        with:
          version: 1.0.*
      - name: Push Sources to Applanga
        if: '${{ inputs.push_targets != true }}'
        env:
          APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
          APPLANGA_API_HOST: ${{ secrets.APPLANGA_API_HOST }}
        run: applanga push --force
        working-directory: checkout
      - name: Push Translation Files to Applanga
        if: '${{ inputs.push_targets == true }}'
        env:
          APPLANGA_ACCESS_TOKEN: '${{ secrets.APPLANGA_ACCESS_TOKEN }}'
        run: applanga pushtarget --force
        working-directory: checkout
      - name: Notify workflow success
        if: success()
        run: |-
          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ steps.extract-app-id.outputs.MOBILE_APP_ID }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
            -d '{
            "branchId": "${{ github.event.inputs.branch_id }}",
            "workflowType": "push",
              "status": "success"
            }' || echo "Failed to notify workflow success"
      - name: Notify workflow failure
        if: failure()
        run: |-
          curl -X POST "${{ secrets.APPLANGA_API_HOST }}/v1/api/workflow-complete?app=${{ steps.extract-app-id.outputs.MOBILE_APP_ID }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.APPLANGA_ACCESS_TOKEN }}" \
            -d '{
            "branchId": "${{ github.event.inputs.branch_id }}",
            "workflowType": "push",
              "status": "failed"
            }' || echo "Failed to notify workflow failure"
